// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE
recipes.remove(<techreborn:grinder>);
recipes.remove(<actuallyadditions:block_grinder>);
recipes.remove(<actuallyadditions:block_grinder>);
recipes.remove(<extrautils2:teleporter:1>);
recipes.remove(<dungeontactics:iron_ring>);
recipes.remove(<inventorypets:nugget_coal>);
recipes.remove(<jaopca:item_nuggetcoal>);
recipes.remove(<ghostsexplosives:dust_charcoal>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<icbmclassic:explosives:22>);
recipes.remove(<icbmclassic:explosives:22>);
recipes.remove(<icbmclassic:explosives:23>);
recipes.remove(<icbmclassic:explosives:23>);
recipes.remove(<icbmclassic:explosives:23>);
recipes.remove(<icbmclassic:explosives:23>);
recipes.remove(<icbmclassic:launcherbase:1>);
recipes.remove(<icbmclassic:launcherbase:1>);
recipes.remove(<icbmclassic:launcherframe>);
recipes.remove(<icbmclassic:launcherframe>);
recipes.remove(<icbmclassic:launcherbase>);
recipes.remove(<icbmclassic:launcherbase>);
recipes.remove(<icbmclassic:launcherbase>);
recipes.remove(<icbmclassic:explosives:1>);
recipes.remove(<icbmclassic:explosives:1>);
recipes.remove(<icbmclassic:explosives:1>);
recipes.remove(<icbmclassic:explosives:22>);
recipes.remove(<icbmclassic:explosives:22>);
recipes.remove(<icbmclassic:explosives:22>);
recipes.remove(<icbmclassic:explosives>);
recipes.remove(<icbmclassic:explosives:15>);
recipes.remove(<icbmclassic:explosives:15>);
recipes.remove(<icbmclassic:explosives:15>);
recipes.remove(<icbmclassic:explosives:23>);
recipes.remove(<icbmclassic:explosives:23>);
recipes.remove(<icbmclassic:explosives:23>);
recipes.remove(<icbmclassic:explosives:23>);
recipes.remove(<akashictome:tome>);
recipes.remove(<akashictome:tome>);
recipes.remove(<akashictome:tome>);
recipes.remove(<akashictome:tome>);
recipes.remove(<portalgun:item_portalgun>);
recipes.remove(<portalgun:item_portalgun>);
recipes.remove(<portalgun:item_portalgun>);
recipes.remove(<portalgun:item_portalgun>);
recipes.remove(<ghostsexplosives:tnt_nuclear>);
recipes.remove(<ghostsexplosives:tnt_nuclear>);
recipes.remove(<ghostsexplosives:tnt_nuclear>);
recipes.remove(<ghostsexplosives:tnt_nuclear>);
recipes.remove(<ghostsexplosives:tnt_nuclear>);
recipes.remove(<ghostsexplosives:tnt_nuclear>);
recipes.remove(<ghostsexplosives:tnt_nuclear>);
recipes.remove(<ghostsexplosives:tnt_nuclear>);
recipes.remove(<ghostsexplosives:tnt_nuclear>);
recipes.remove(<ghostsexplosives:tnt_nuclear>);
recipes.remove(<mekanism:salt>);
recipes.remove(<mekanism:salt>);
recipes.remove(<mekanism:salt>);
recipes.remove(<mekanism:salt>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<powersuits:powerarmor_torso>);
recipes.remove(<powersuits:powerarmor_torso>);
recipes.remove(<powersuits:powerarmor_torso>);
recipes.remove(<powersuits:powerarmor_torso>);
recipes.remove(<powersuits:power_fist>);
recipes.remove(<powersuits:power_fist>);

// ================================================================================
//#MARKER REMOVE SHAPELESS
recipes.removeShapeless(<jaopca:item_nuggetcoal> * 9, [<minecraft:coal>]);
recipes.removeShapeless(<inventorypets:nugget_coal> * 8, [<minecraft:coal>]);

// ================================================================================
//#MARKER REMOVE SHAPED
recipes.removeShaped(<ghostsexplosives:dust_charcoal> * 2, [[<ore:itemCharcoal>]]);
recipes.removeShaped(<icbmclassic:launcherbase:1>, [[<mekanism:ingot>, <techreborn:cable:6>, <mekanism:ingot>], [<mekanism:ingot>, <icbmclassic:launcherbase>, <mekanism:ingot>], [<mekanism:ingot>, <techreborn:lapotroncrystal>, <mekanism:ingot>]]);
recipes.removeShaped(<icbmclassic:launcherbase:1>, [[<mekanism:ingot>, <techreborn:cable:6>, <mekanism:ingot>], [<mekanism:ingot>, <icbmclassic:launcherbase>, <mekanism:ingot>], [<mekanism:ingot>, <techreborn:lapotroncrystal>, <mekanism:ingot>]]);
recipes.removeShaped(<powersuits:powerarmor_torso>, [[<techreborn:plates:36>, null, <techreborn:plates:36>], [<techreborn:plates:38>, <mekanismtools:osmiumchestplate>, <techreborn:plates:38>], [<techreborn:plates:36>, <techreborn:part:43>, <techreborn:plates:36>]]);
recipes.removeShaped(<powersuits:powerarmor_torso>, [[<techreborn:plates:36>, null, <techreborn:plates:36>], [<techreborn:plates:38>, <mekanismtools:osmiumchestplate>, <techreborn:plates:38>], [<techreborn:plates:36>, <techreborn:part:43>, <techreborn:plates:36>]]);
recipes.removeShaped(<powersuits:powerarmor_torso>, [[<techreborn:plates:36>, null, <techreborn:plates:36>], [<techreborn:plates:38>, <mekanismtools:osmiumchestplate>, <techreborn:plates:38>], [<techreborn:plates:36>, <techreborn:part:43>, <techreborn:plates:36>]]);
recipes.removeShaped(<powersuits:powerarmor_torso>, [[<techreborn:plates:36>, null, <techreborn:plates:36>], [<techreborn:plates:38>, <mekanismtools:osmiumchestplate>, <techreborn:plates:38>], [<techreborn:plates:36>, <techreborn:part:43>, <techreborn:plates:36>]]);
recipes.removeShaped(<powersuits:powerarmor_torso>, [[<techreborn:plates:36>, null, <techreborn:plates:36>], [<techreborn:plates:38>, <mekanismtools:osmiumchestplate>, <techreborn:plates:38>], [<techreborn:plates:36>, <techreborn:part:43>, <techreborn:plates:36>]]);

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
recipes.addShapeless(<inventorypets:nugget_coal> * 8, [<immersiveengineering:tool>, <ore:itemCoal>]);
recipes.addShapeless(<ghostsexplosives:dust_charcoal> * 2, [<ore:toolMortarandpestle>, <ore:itemCharcoal>]);
recipes.addShapeless(<icbmclassic:explosives:23>, [<ore:compressed8xCobblestone>, <ore:compressed8xCobblestone>, <ore:compressed8xCobblestone>, <ore:compressed8xCobblestone>, <tconstruct:shard>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>]);


// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<dungeontactics:iron_ring>, [[<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>], [<minecraft:iron_nugget>, null, <ore:nuggetIron>], [<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>]]);
recipes.addShaped(<powersuits:tinkertable>, [[<ore:ingotKnightmetal>, <rats:arcane_technology>, <ore:ingotKnightmetal>], [<enderio:item_alloy_ingot>, <twilightforest:knightmetal_ingot>, <ore:ingotElectricalSteel>], [<ore:ingotElectricalSteel>, <ore:ingotKnightmetal>, <ore:ingotElectricalSteel>]]);
//recipes.addShaped(<mystcraft:writingdesk>, [[null, <minecraft:carpet:14>, null], [<minecraft:bookshelf>, <ore:netherStar>, <minecraft:bookshelf>], [<ore:bookshelf>, <minecraft:log>, <ore:bookshelf>]]);
recipes.addShaped(<techreborn:chunk_loader>, [[<techreborn:part:5>, <ore:enderpearl>, <techreborn:part:5>], [<mekanism:ingot>, <techreborn:part:41>, <ore:ingotRefinedObsidian>], [<ore:lapotronCrystal>, <techreborn:plates:32>, <ore:lapotronCrystal>]]);
//recipes.addShaped(<mystcraft:blockinkmixer>, [[<minecraft:carpet:15>, null, null], [<minecraft:stone>, <minecraft:nether_star>, <minecraft:stone>], [<minecraft:stone>, null, <minecraft:stone>]]);
//recipes.addShaped(<mystcraft:writingdesk>, [[<ore:plankWood>, <ore:plankWood>, <ore:plankWood>], [<ore:plankWood>, <minecraft:dragon_egg>, <ore:plankWood>]]);
//recipes.addShaped(<techreborn:ingot:14>;
recipes.addShaped(<icbmclassic:explosives:22>, [[<techreborn:ingot:25>, <techreborn:plates:38>, <techreborn:ingot:25>], [<extrautils2:compressedcobblestone:7>, <icbmclassic:explosives:15>, <extrautils2:compressedcobblestone:7>], [<techreborn:ingot:25>, <minecraft:bedrock>, <techreborn:ingot:25>]]);
recipes.addShaped(<icbmclassic:explosives:23>, [[<extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>], [<extrautils2:compressedcobblestone:7>, <icbmclassic:explosives:15>, <extrautils2:compressedcobblestone:7>], [<extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>]]);
recipes.addShaped(<icbmclassic:launcherbase:1>, [[<mekanism:ingot>, <techreborn:cable:6>, <mekanism:ingot>], [<mekanism:ingot>, <icbmclassic:launcherbase>, <mekanism:ingot>], [<mekanism:ingot>, <techreborn:lapotroncrystal>, <mekanism:ingot>]]);
recipes.addShaped(<icbmclassic:launcherbase:1>, [[<mekanism:ingot>, <techreborn:cable:6>, <mekanism:ingot>], [<mekanism:ingot>, <icbmclassic:launcherbase>, <mekanism:ingot>], [<mekanism:ingot>, <techreborn:lapotroncrystal>, <mekanism:ingot>]]);
recipes.addShaped(<icbmclassic:launcherframe>, [[<techreborn:plates:2>, <techreborn:cable:6>, <techreborn:plates:2>], [<techreborn:plates:2>, null, <techreborn:plates:2>], [<techreborn:plates:2>, <techreborn:lapotroncrystal>, <techreborn:plates:2>]]);
recipes.addShaped(<icbmclassic:launcherbase>, [[<techreborn:plates:2>, null, <techreborn:plates:2>], [<techreborn:plates:2>, <techreborn:cable:6>, <techreborn:plates:2>], [<techreborn:plates:2>, <techreborn:lapotroncrystal>, <techreborn:plates:2>]]);
recipes.addShaped(<icbmclassic:explosives:1>, [[<techreborn:cable:6>, <ore:plateCarbon>, <ore:insulatedGoldCableItem>], [<ore:plateCarbon>, <icbmclassic:explosives>, <ore:plateCarbon>], [<ore:insulatedGoldCableItem>, <techreborn:plates:2>, <ore:insulatedGoldCableItem>]]);
recipes.addShaped(<icbmclassic:explosives:22>, [[<extrautils2:compressednetherrack:5>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressednetherrack:5>], [<extrautils2:compressednetherrack:5>, <tconstruct:shard>, <extrautils2:compressednetherrack:5>], [<extrautils2:compressednetherrack:5>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressednetherrack:5>]]);
recipes.addShaped(<icbmclassic:explosives>, [[<mekanism:obsidiantnt>, <mekanism:ingot>, <mekanism:obsidiantnt>], [<mekanism:ingot>, <ghostsexplosives:tnt_x100>, <mekanism:ingot>], [<mekanism:obsidiantnt>, <mekanism:ingot>, <mekanism:obsidiantnt>]]);
recipes.addShaped(<icbmclassic:explosives:15>, [[<techreborn:ingot:25>, <techreborn:plates:38>, <techreborn:ingot:25>], [<techreborn:plates:38>, <ghostsexplosives:tnt_nuclear>, <techreborn:plates:38>], [<techreborn:ingot:25>, <techreborn:plates:38>, <techreborn:ingot:25>]]);
recipes.addShaped(<akashictome:tome>, [[<minecraft:stick>]]);
recipes.addShaped(<portalgun:item_portalgun>, [[<actuallyadditions:block_crystal:2>, <twilightforest:knightmetal_ingot>, <twilightforest:knightmetal_ingot>], [<wrcbe:rep>, <portalgun:item_miniature_black_hole>, <twilightforest:knightmetal_ingot>], [<twilightforest:knightmetal_ingot>, <actuallyadditions:block_crystal:2>, <ore:ingotKnightmetal>]]);
recipes.addShaped(<ghostsexplosives:tnt_nuclear>, [[<ghostsexplosives:tnt_x1000>, <ghostsexplosives:block_uranium>, <ghostsexplosives:tnt_x1000>], [<ghostsexplosives:block_uranium>, <ore:depletedFuelHECf251Oxide>, <ghostsexplosives:block_uranium>], [<ghostsexplosives:tnt_x1000>, <ghostsexplosives:block_uranium>, <ghostsexplosives:tnt_x1000>]]);
recipes.addShaped(<powersuits:tinkertable>, [[<ore:plateEmerald>, <rats:arcane_technology>, <ore:plateEmerald>], [<ore:ingotSteel>, <ore:skullZombieElectrode>, <ore:ingotSteel>], [<ore:ingotSteel>, <enderio:item_material:20>, <thermalfoundation:material:160>]]);
recipes.addShaped(<powersuits:powerarmor_torso>, [[<techreborn:plates:36>, null, <techreborn:plates:36>], [<techreborn:plates:38>, <mekanismtools:osmiumchestplate>, <techreborn:plates:38>], [<techreborn:plates:36>, <techreborn:part:43>, <techreborn:plates:36>]]);
recipes.addShaped(<powersuits:powerarmor_torso>, [[<ore:plateadvancedAlloy>, null, <techreborn:plates:36>], [<techreborn:plates:38>, <conarm:chest_core>, <techreborn:plates:38>], [<ore:plateadvancedAlloy>, <techreborn:part:43>, <techreborn:plates:36>]]);
recipes.addShaped(<powersuits:power_fist>, [[<ore:ingotEndSteel>, <openmodularturrets:intermediate_tiered:9>, <enderio:item_alloy_ingot:8>], [null, <techreborn:advanceddrill>, null], [null, <ore:ingotVibrantAlloy>, null]]);
recipes.addShaped(<thermalfoundation:material:160>, [[<ore:dustObsidian>, <ore:dustCoal>, <ore:dustObsidian>], [<ore:dustCoal>, <ore:ingotBrass>, <ore:dustCoal>], [<ore:dustObsidian>, <ore:dustCoal>, <thermalfoundation:material:770>]]);

