name: Bug Report
description: For issues such as "X happens instead of Y"
title: "[BUG] *Replace with brief description of the issue*"
labels: "[bug]"
body:
  - type: markdown
    attributes:
      value: |
        If the issue is a Crash or Question, please ask in the Discord first https://discord.gg/ZS6FRR3
  - type: textarea
    id: bug-desc
    attributes:
      label: Description of the Bug
      description: Description of effects of the bug, and what actually happened.
      placeholder: |
        Causes X to do Z instead of Y
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: What you expected to happen.
      placeholder: |
        1. Go to X
        2. Click on Y
        3. Z occurs
    validations:
      required: true
  - type: input
    id: version-info
    attributes:
      label: Modpack Version
      description: Please do not put "Latest", that is useless info.
      placeholder: 1.4.4, 1.5-RC
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: Screenshots of the issue, if applicable.
    validations:
      required: false
  - type: input
    id: log
    attributes:
      label: Log
      description: Not required for all types of issues, do not include if not applicable.
      placeholder: Link from paste.gg, gist.github.com, etc.
    validations:
      required: false
  - type: textarea
    id: extra-info
    attributes:
      label: Extra Info
      description: Any extra information about your instance of MC Eternal, such as additional mods not in the base pack. Please note that support on Altered instances is limited.
      placeholder: |
        Extra Mods: somerandommod-1.12.2-1.6.3, someotherrandommod-1.3.4-1.86
        Configs changed: Changed X in Y.cfg
    validations:
      required: false
